### ISSUE TITLE
Split out choice lists to lookup tables

### ISSUE THREAD

**Issue by spatialguerilla** [CenturyGIS/sequelize-auto-fulcrum#2]
@eczajk1 - One thing that could be done is to translate the choices / values of choice lists and yes/no fields into lookup table models.  This would ease info-window / web app rendering by eliminating the need to hard code these translations into the app source code.

**Comment by eczajk1** [comment]
Interesting idea. It could be done.

This would require a separate webhook mechanism for loading the "choice" data and keeping it up-to-date. This is also not something that Fulcrum does with its data-exports, which makes me a little reluctant to implement it.

If I understand the overall need, it is that we want to be able to have a key/value store for these fields so that we have an easy way to render them on the client. I can think of some other ways of dealing with this though without modifying the database (e.g. use the Fulcrum form to create a JSON store of key/values, per field).

If the need is that the database needs to be more complete by having these values stored and kept up-to-date there, then that is a separate need, that we could look into as well.

**Comment by spatialguerilla** [comment]
The JSON store seems like a good alternative. My primary intent was to simplify the lookup translation process, but with that comes the need to keep these key-values up-to-date.  Perhaps something to explore at a later point
